-- Create the main table
CREATE TABLE SALES_DATA (
    ID NUMBER PRIMARY KEY,
    SALE_AMOUNT NUMBER,
    SALE_DATE DATE,
    CUSTOMER_NAME VARCHAR2(100)
);

-- Load 1 Million Records
INSERT /*+ APPEND */ INTO SALES_DATA (ID, SALE_AMOUNT, SALE_DATE, CUSTOMER_NAME)
SELECT 
    level AS ID,
    ROUND(DBMS_RANDOM.VALUE(10, 1000), 2) AS SALE_AMOUNT,
    SYSDATE - DBMS_RANDOM.VALUE(0, 365) AS SALE_DATE,
    'CUSTOMER_' || level AS CUSTOMER_NAME
FROM dual
CONNECT BY level <= 1000000;

COMMIT;

-- Take the Snapshot
CREATE TABLE SALES_DATA_SNAPSHOT AS SELECT * FROM SALES_DATA;
